"""Create authors, posts tables

Revision ID: 51b0d8083141
Revises: faa482c1e292
Create Date: 2024-01-14 20:19:33.021343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b0d8083141'
down_revision = 'faa482c1e292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
